project:
  type: website
  output-dir: docs

website:
  title: "Adilene Garibay"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
      - text: "CV"
        href: cv.qmd
      - text: "EPPS6302 Assignments"
        menu:
          - text: "Assignment 1"
            href: assign01.qmd
          - text: "Assignment 2"
            href: assgn.2.qmd
          - text: "Assignment 3"
            href: assgn3.qmd
      - text: "EPPS 6302 Prepare for Class"
        menu:
          - text: "Prepare for Class 3"
            href: prepclass.3.qmd
          - text: "Prepare for Class 4"
            href: prpclss4.qmd
      - text: "EPPS Data Visualization Prepare for Class"
        menu: 
          - text: "Prepare for Class #3"
            href: prpclss3dv.qmd
      - text: "EPPS Data Visualization Assignments"
        menu: 
          - text: "Assignment #1"
            href: assgn1dv.qmd
          - text: "Assignment #2 Murell"
            href: Assignment2murrell.qmd
          - text: "Assignment #2 HPI"
            href: Assignment2HPI.qmd
          - text: "Assignment #4 Hackathon"
            href: hackathon.qmd

format:
  html:
    theme: cosmo
    toc: true