project:
  type: website
  output-dir: docs

website:
  title: "Adilene Garibay"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
      - text: "CV"
        href: cv.html

format:
  html:
    theme: cosmo
    toc: true