project:
  type: website
  output-dir: docs

website:
  title: "Adilene Garibay"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
      - text: "CV"
        href: cv.qmd
      - text: "EPPS6302 Assignments"
        menu:
          - text: "Assignment 1"
            href: assign01.qmd

      - text: "Prepare for Class"
        menu:
          - text: "Prepare for Class 3"
            href: prepclass.3.qmd
      - text: "EPPS Data Visualization"
        menu:
          - text: "Project"
            href: brainstorm.qmd

format:
  html:
    theme: cosmo
    toc: true