project:
  type: website
  output-dir: docs

website:
  title: "Adilene Garibay"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
      - text: "CV"
        href: cv.qmd
      - text: "Assignments"
        menu:
          - text: "Assignment 01"
            href: assign01.qmd
          - text: "Assignment 02"
            href: assign02.qmd

format:
  html:
    theme: cosmo
    toc: true