---
title: "Assignment 6 Quanteda"
format: html
editor: visual
---

## Text Analytics Using Quanteda

-   [x] Read about the package.

-   [x] Analyse Biden-Xi Summit data.

    -   [x] The outputs for this data shows connection between the nodes :"biden", "coronavirus", "fentanyl", "america","jobiden","china","xijinping","biden", and "americans". These terms form their own cluster and the line which connects them is thicker than the connection of other nodes. There is also a cluster associated the terms "uyghurs", "urghurgenocide","humanrights","xi","tibetans". However, this cluster is not as central as the one stated previously. It is connected to the "jobiden" node which makes sense given because that is a topic that Joe Biden brought up.

-   [x] US Presidential Inaugural Speeches.

    -   [x] The data here shows several graphics. The graphics represent key terms associated with inaugural addresses. The terms which are most prominent are "government", "great", "states", "country", "peace", "citizen", ect.. Terms like these are larger in font compared to terms that may not be so prominent, such as "authority".

    -   [x] Looking at the Lexical Dispersion plot, it seems like the term "american" is more frequently used by presidents over time. More recently, there is less dispersion in the use of the term. Aditionally, President Trump, in both terms uses the term more frequently than other Presidents.

-   [x] Wordfish: Wordfish is a Poisson scaling model (a statistical method used to find a hidden, continuous dimension from count data, such as word frequencies in documents) of one-dimensional document positions (Slapin and Proksch 2008). Allows for scaling documents. Compared to Wordscores, reference scores/texts are not required. It is an unsupervised one-dimensional scaling method, which means that is estimates the positions of documents solely based on the observed word frequencies.
