---
title: "Assignment 1"
editor: visual
format:
  html:
    theme: cosmo
    mainfont: "Georgia"
    fontsize: 1.1em
    fontcolor: "#333333"
    linestretch: 1.6
---

## 1. Setting up

a\. Read “Creating a Quarto Website and Deploying on GitHub Pages”

b\. Install quarto in R i. In RStudio console, type: install.packages("quarto") and run ii. In RStudio terminal, type: quarto install, and enter.

c\. Create a New Project, choose New Directory and Quarto Website d. RStudio tutorial (with video): https://quarto.org/docs/get-started/hello/rstudio.html

## 2. Note

## 3. Include your updated CV/Resume on your navigation bar.

## 4. Write a one page not on designing your website:

Submission: This Website is created using Rstudio Quarto. The theme is used for a professional look. The navigation bar includes CV, About, and Assignment links for connecting the author's content in different areas.

## 5. Once done, send your website url to the instructor:

a\. Subject: Your name website

b\. The url should look like: karlho.github.io, johndoe11.github.io, in which karlho, johndoe11 are the username for GitHub login.
